# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml

-   repo: https://github.com/PyCQA/isort
    rev: 4.3.21
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
