language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - >
    conda create -q -c conda-forge -c defaults -n Newton-Krylov_OOC python=$TRAVIS_PYTHON_VERSION
    black flake8 gitpython isort netCDF4 numpy pint pytest pyyaml scipy

script:
  - ./scripts/travis_short.sh
  - ./scripts/travis_zero_iage.sh
  - ./scripts/travis_long_iage.sh
  - ./scripts/travis_long_dye_decay.sh
