name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - run: |
          if [[ ${{ matrix.python-version }} == 3.7 ]] ; then
            conda create -q -c conda-forge -c defaults -n Newton-Krylov_OOC \
              python=${{ matrix.python-version }} \
              black flake8 "isort<5.12" "zipp<3.16.0" "more-itertools<10.0.0" netCDF4 xarray numpy pint pytest pyyaml scipy
          elif [[ ${{ matrix.python-version }} == 3.8 ]] ; then
            conda create -q -c conda-forge -c defaults -n Newton-Krylov_OOC \
              python=${{ matrix.python-version }} \
              black flake8 isort netCDF4 xarray numpy "pint<0.22" pytest pyyaml scipy
          else
            conda create -q -c conda-forge -c defaults -n Newton-Krylov_OOC \
              python=${{ matrix.python-version }} \
              black flake8 isort netCDF4 xarray numpy pint pytest pyyaml scipy
          fi
      - uses: actions/checkout@v2
      - run: ./scripts/ci_short.sh
      - run: ./scripts/ci_zero_iage.sh
      - run: ./scripts/ci_long_iage.sh
      - run: ./scripts/ci_long_dye_decay.sh
      - run: ./scripts/ci_py_driver_2d_iage.sh
      - run: ./scripts/ci_py_driver_2d_iage_column_regions.sh
