name: push-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: wget -O Miniforge3.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh
      - run: bash Miniforge3.sh -b
