name: push-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: conda init bash
      - run: conda install mamba -n base -c conda-forge
      - run: conda activate base
      - run: mamba create -q -c conda-forge -c defaults -n Newton-Krylov_OOC black flake8 isort netCDF4 numpy pint pytest pyyaml scipy
      - uses: actions/checkout@v2
      - run: ./scripts/travis_short.sh
